# Generated by Django 4.0.4 on 2022-05-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_slide1', models.TextField()),
                ('slide_2', models.TextField()),
                ('slide_3', models.TextField()),
                ('slide_4', models.TextField()),
                ('offer_day', models.IntegerField()),
            ],
            options={
                'db_table': 'app',
                'managed': False,
            },
        ),
    ]
