# Generated by Django 4.0.4 on 2022-05-31 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cauhoi', models.TextField()),
                ('rep', models.TextField()),
            ],
            options={
                'db_table': 'faq',
                'managed': False,
            },
        ),
    ]
